swagger: "2.0"
info:
  description: "This is the Swagger API Documentation for InternManager Web Application"
  version: "1.0.0"
  title: "InternManager"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "s541910@nwmissouri.edu"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "https://intermanager-ui.herokuapp.com/#/register"
basePath: "/im/api"
tags:
- name: "user"
  description: "User Login Credentials"
- name: "Faculty"
  description: ""

schemes:
- "https"

paths:
  /majors:
    get:
      tags:
      - "major"
      summary: "Get a list of all the majors"
      description: ""
      operationId: "getMajors"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "404":
          description: "Not found"
		  
	/applications:
    get:
      tags:
      - "Application"
      summary: "Get a list of all the applications"
      description: ""
      operationId: "getApplications"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "404":
          description: "Not found"	  
		  
	/application/id:
    get:
      tags:
      - "Application Based On Id"
      summary: "Get the application based on Id"
      description: ""
      operationId: "getInternshipData"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "404":
          description: "Not found"	

	/student/personalDetails/:studentId:
    get:
      tags:
      - "Student personla Based On Id"
      summary: "Get the Student details based on Id"
      description: ""
      operationId: "getPersonalDetails"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "404":
          description: "Not found"

	/student/comments/:applicationId:
    get:
      tags:
      - "Comments Based On StudentId"
      summary: "Get the Comments Based On StudentId"
      description: ""
      operationId: "getComments"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "404":
          description: "Not found"	

	/verifyfaculty/:id:
    get:
      tags:
      - "Verify Faulty Based On Id"
      summary: "Get the Faulty Based On Id"
      description: ""
      operationId: "getFaculty"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "404":
          description: "Not found"		
		  
		  

    post:
      tags:
      - "user"
      summary: "Add user login credentials"
      description: ""
      operationId: "postUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "userName"
        in: "query"
        description: ""
        required: true
        type: "string"
      - name: "email"
        in: "query"
        description: ""
        required: true
        type: "string"
      - name: "password"
        in: "query"
        description: ""
        required: true
        type: "string"    
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/user"
        "400":
          description: "Invalid status value"


  /locations:
    get:
      tags:
      - "location"
      summary: "Get a list of all the Locations"
      description: ""
      operationId: "getLocations"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "405":
          description: "Invalid input"

    post:
      tags:
      - "login"
      summary: "Login"
      description: ""
      operationId: "login"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - email: "email"
        in: "query"
        description: ""
        required: true
        type: "string"
		
	  - password: "password"
	    in: "query"
        description: ""
        required: true
        type: "string"
	   
	   responses:
        "200":
          description: "successful login"
          schema:
            type: "array"
            items:
              $ref: "#/login"
        "400":
          description: "Invalid status value"
		  
	 post:
      tags:
      - "register"
      summary: "Register"
      description: ""
      operationId: "register"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - email: "email"
        in: "query"
        description: ""
        required: true
        type: "string"
		
	  - password: "password"
	    in: "query"
        description: ""
        required: true
        type: "string"
		
	  - firstname: "firstname"
	    in: "query"
        description: ""
        required: true
        type: "string"
		
	  - lastname: "lastname"
	    in: "query"
        description: ""
        required: true
        type: "string"
		
	   responses:
        "200":
          description: "successful Register"
          schema:
            type: "array"
            items:
              $ref: "#/register"
        "400":
          description: "Invalid status value"	  


  


 post:
      tags:
      - "studentdata"
      summary: "studentdata"
      description: ""
      operationId: "studentdata"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - addressLine1: "addressLine1"
        in: "query"
        description: ""
        required: true
        type: "string"
		
	  - addressLine2: "addressLine2"
	    in: "query"
        description: ""
        required: true
        type: "string"
		
	  - city: "city"
	    in: "query"
        description: ""
        required: true
        type: "string"
		
	  - state: "state"
	    in: "query"
        description: ""
        required: true
        type: "string"
		
		- contact: "contact"
	    in: "query"
        description: ""
        required: true
        type: "string"
		
		- majorId: "majorId"
	    in: "query"
        description: ""
        required: true
        type: "string"
		
		- studentId: "studentId"
	    in: "query"
        description: ""
        required: true
        type: "string"
		
	   responses:
        "200":
          description: "successful Register"
          schema:
            type: "array"
            items:
              $ref: "#/studentdata"
        "400":
          description: "Invalid status value"	


post:
      tags:
      - "addInternshipApplication"
      summary: "addInternshipApplication"
      description: ""
      operationId: "addInternshipApplication"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - applicationStatus: "applicationStatus"
        in: "query"
        description: ""
        required: true
        type: "string"
		
	  - applicationDate: "applicationDate"
	    in: "query"
        description: ""
        required: true
        type: "string"
		
	  - approvedBy: "approvedBy"
	    in: "query"
        description: ""
        required: true
        type: "string"
		
	  - comments: "comments"
	    in: "query"
        description: ""
        required: true
        type: "string"
		
		- startDate: "startDate"
	    in: "query"
        description: ""
        required: true
        type: "string"
		
		- endDate: "endDate"
	    in: "query"
        description: ""
        required: true
        type: "string"
		
		- pushNotification: "pushNotification"
	    in: "query"
        description: ""
        required: true
        type: "string"
		
		- employerName: "employerName"
	    in: "query"
        description: ""
        required: true
        type: "string"
		
		
		- primaryContactName: "primaryContactName"
	    in: "query"
        description: ""
        required: true
        type: "string"
		
		- email: "email"
	    in: "query"
        description: ""
        required: true
        type: "string"
		
	   responses:
        "200":
          description: "successful Register"
          schema:
            type: "array"
            items:
              $ref: "#/addInternshipApplication"
        "400":
          description: "Invalid status value"


 post:
      tags:
      - "comments"
      summary: "comments"
      description: ""
      operationId: "comments"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - StudentId: "StudentId"
        in: "query"
        description: ""
        required: true
        type: "string"
			
	   responses:
        "200":
          description: "successful Register"
          schema:
            type: "array"
            items:
              $ref: "#/register"
        "400":
          description: "Invalid status value"	
patch:
		tags:
      - "update-applications-status/:id"
      summary: "applications Status update"
      description: ""
      operationId: "applications Status update"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - StudentId: "StudentId"
        in: "query"
        description: ""
        required: true
        type: "string"
		
		- applicationId: "applicationId"
        in: "query"
        description: ""
        required: true
        type: "string"
	   responses:
        "200":
          description: "successful Saved"
          schema:
            type: "array"
            items:
              $ref: "#/update-applications-status/:id"
        "400":
          description: "Invalid status value"	



patch:
      tags:
      - "student/updateapplicationdata/:id"
      summary: "update application based on id"
      description: ""
      operationId: "student/updateapplicationdata/:id"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - applicationStatus: "applicationStatus"
        in: "query"
        description: ""
        required: true
        type: "string"
		
	  - applicationDate: "applicationDate"
	    in: "query"
        description: ""
        required: true
        type: "string"
		
	  - approvedBy: "approvedBy"
	    in: "query"
        description: ""
        required: true
        type: "string"
		
	  - comments: "comments"
	    in: "query"
        description: ""
        required: true
        type: "string"
		
		- startDate: "startDate"
	    in: "query"
        description: ""
        required: true
        type: "string"
		
		- endDate: "endDate"
	    in: "query"
        description: ""
        required: true
        type: "string"
		
		- pushNotification: "pushNotification"
	    in: "query"
        description: ""
        required: true
        type: "string"
		
		- employerName: "employerName"
	    in: "query"
        description: ""
        required: true
        type: "string"
		
		
		- primaryContactName: "primaryContactName"
	    in: "query"
        description: ""
        required: true
        type: "string"
		
		- email: "email"
	    in: "query"
        description: ""
        required: true
        type: "string"
		
	   responses:
        "200":
          description: "successful Register"
          schema:
            type: "array"
            items:
              $ref: "#/student/updateapplicationdata/:id"
        "400":
          description: "Invalid status value"


definitions:
  users:
    type: "object"
    properties:
      userName:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
	 firstname:
        type: "string"
	 lastname:
        type: "string"

  internships:
    type: "object"
    properties:
      employerName:
        type: "string"
      primaryContactName:
        type: "string"
      email:
        type: "string"
      duration:
        type: "string"
      employerContact:
        type: "string"
		addressLine1:
        type: "string"
		addressLine2:
        type: "string"
		city:
        type: "string"
		state:
        type: "string"
		zipCode:
        type: "string"
		
	applications:
   	type: "object"
    properties:
      applicationStatus:
        type: "string"
      applicationDate:
        type: "string"
      approvedBy:
        type: "string"
      comments:
        type: "string"
		
   majors:
   	type: "object"
    properties:
      major_Id:
        type: "string"
      majorName:
        type: "string"
      category:
        type: "string"
      
    	
   student_details:
   	type: "object"
    properties:
      addressLine1:
        type: "string"
      addressLine2:
        type: "string"
      city:
        type: "string"	
state:
        type: "string"
zipCode:
        type: "string"
contact:
        type: "string"
		
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
